version: 0.2

env:
  secrets-manager:
    DATABRICKS_TOKEN: "databricks-dummy-token-cicd-demo:DATABRICKS_TOKEN"

phases:
  pre_build:
    commands:
      - |
        case "$CODEBUILD_WEBHOOK_HEAD_REF" in
          refs/heads/main) export BUNDLE_TARGET=prod ; export DATABRICKS_HOST=$DATABRICKS_HOST_PROD ;;
          refs/heads/uat)  export BUNDLE_TARGET=uat ; export DATABRICKS_HOST=$DATABRICKS_HOST_UAT ;;
          *)                export BUNDLE_TARGET=dev ; export DATABRICKS_HOST=$DATABRICKS_HOST_DEV ;;
        esac
  build:
    commands:
      - python PFL_EXECUTE/dummy_execute_script.py
