version: 0.2

env:
  secrets-manager:
    DATABRICKS_TOKEN: "databricks-dummy-token-cicd-demo:DATABRICKS_TOKEN"

phases:
  install:
    commands:
      - pip install databricks-cli databricks-sdk
      - curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
  pre_build:
    commands:
      - export DATABRICKS_HOST=$DATABRICKS_HOST_DEV
  build:
    commands:
      - databricks bundle validate -t dev
      - python -m py_compile PFL_EXECUTE/dummy_execute_script.py
